import { defineConfig, globalIgnores } from "eslint/config";
import pluginReact from "eslint-plugin-react";

export default defineConfig([
  pluginReact.configs.flat.recommended,
  globalIgnores(["dist/**", "node_modules/**", ".yarn/*", "**/*.{cjs,mjs}"]),
  {
    files: ["**/*.{js,ts,jsx,tsx}"],
    rules: {
      "accessor-pairs": "off",
      "array-callback-return": "error",
      "block-scoped-var": "error",
      complexity: ["off", 11],
      "class-methods-use-this": ["error", { exceptMethods: [] }],
      "consistent-return": "error",
      curly: ["error", "multi-line"],
      "default-case": ["error", { commentPattern: "^no default$" }],
      "dot-notation": ["error", { allowKeywords: true }],
      "dot-location": ["error", "property"],
      eqeqeq: ["error", "always", { null: "ignore" }],
      "guard-for-in": "error",
      "no-alert": "warn",
      "no-caller": "error",
      "no-case-declarations": "error",
      "no-div-regex": "off",
      "no-else-return": "error",
      "no-empty-function": [
        "error",
        { allow: ["arrowFunctions", "functions", "methods"] },
      ],
      "no-empty-pattern": "error",
      "no-eq-null": "off",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-fallthrough": "error",
      "no-floating-decimal": "error",
      "no-global-assign": ["error", { exceptions: [] }],
      "no-implicit-coercion": [
        "off",
        { boolean: false, number: true, string: true, allow: [] },
      ],
      "no-implicit-globals": "off",
      "no-implied-eval": "error",
      "no-invalid-this": "off",
      "no-iterator": "error",
      "no-labels": ["error", { allowLoop: false, allowSwitch: false }],
      "no-lone-blocks": "error",
      "no-loop-func": "error",
      "no-magic-numbers": [
        "warn",
        {
          ignore: [],
          ignoreArrayIndexes: true,
          enforceConst: true,
          detectObjects: false,
        },
      ],
      "no-multi-spaces": "error",
      "no-multi-str": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-octal": "error",
      "no-octal-escape": "error",
      "no-param-reassign": ["error", { props: true }],
      "no-proto": "error",
      "no-redeclare": "error",
      "no-restricted-properties": "warn",
      "no-return-assign": "error",
      "no-return-await": "error",
      "no-script-url": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-throw-literal": "error",
      "no-unmodified-loop-condition": "off",
      "no-unused-expressions": [
        "error",
        { allowShortCircuit: false, allowTernary: false },
      ],
      "no-unused-labels": "error",
      "no-useless-call": "off",
      "no-useless-concat": "error",
      "no-useless-escape": "error",
      "no-useless-return": "error",
      "no-void": "error",
      "no-warning-comments": [
        "off",
        { terms: ["todo", "fixme", "xxx"], location: "start" },
      ],
      "no-with": "error",
      "prefer-promise-reject-errors": ["off", { allowEmptyReject: true }],
      radix: "error",
      "require-await": "off",
      "vars-on-top": "error",
      "wrap-iife": ["error", "outside", { functionPrototypeMethods: false }],
      yoda: "error",
      "comma-dangle": [
        "error",
        {
          arrays: "always-multiline",
          objects: "always-multiline",
          imports: "always-multiline",
          exports: "always-multiline",
          functions: "always-multiline",
        },
      ],
      "no-await-in-loop": "error",
      "no-cond-assign": ["error", "always"],
      "no-console": "warn",
      "no-constant-condition": "warn",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-dupe-args": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-extra-parens": [
        "off",
        "all",
        {
          conditionalAssign: true,
          nestedBinaryExpressions: false,
          returnAssign: false,
        },
      ],
      "no-extra-semi": "error",
      "no-func-assign": "error",
      "no-inner-declarations": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-obj-calls": "error",
      "no-prototype-builtins": "error",
      "no-regex-spaces": "error",
      "no-sparse-arrays": "error",
      "no-template-curly-in-string": "error",
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "use-isnan": "error",
      "valid-typeof": ["error", { requireStringLiterals: true }],
      "arrow-body-style": [
        "error",
        "as-needed",
        { requireReturnForObjectLiteral: false },
      ],
      "arrow-parens": ["error", "always", { requireForBlockBody: true }],
      "arrow-spacing": ["error", { before: true, after: true }],
      "constructor-super": "error",
      "generator-star-spacing": ["error", { before: false, after: true }],
      "no-class-assign": "error",
      "no-confusing-arrow": ["error", { allowParens: true }],
      "no-const-assign": "error",
      "no-dupe-class-members": "error",
      "no-duplicate-imports": "off",
      "no-new-symbol": "error",
      "no-restricted-imports": "off",
      "no-this-before-super": "error",
      "no-useless-computed-key": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": [
        "error",
        {
          ignoreDestructuring: false,
          ignoreImport: false,
          ignoreExport: false,
        },
      ],
      "no-var": "error",
      "object-shorthand": [
        "error",
        "always",
        { ignoreConstructors: false, avoidQuotes: true },
      ],
      "prefer-arrow-callback": [
        "error",
        { allowNamedFunctions: false, allowUnboundThis: true },
      ],
      "prefer-const": [
        "error",
        { destructuring: "any", ignoreReadBeforeAssign: true },
      ],
      "prefer-destructuring": [
        "off",
        { array: true, object: true },
        { enforceForRenamedProperties: false },
      ],
      "prefer-numeric-literals": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "require-yield": "error",
      "rest-spread-spacing": ["error", "never"],
      "sort-imports": [
        "off",
        {
          ignoreCase: false,
          ignoreMemberSort: false,
          memberSyntaxSortOrder: ["none", "all", "multiple", "single"],
        },
      ],
      "symbol-description": "error",
      "template-curly-spacing": "error",
      "yield-star-spacing": ["error", "after"],
      "global-require": "error",
      "no-new-require": "error",
      "no-path-concat": "error",
      "no-process-env": "off",
      "no-process-exit": "off",
      "no-restricted-modules": "off",
      strict: ["error", "never"],
      "init-declarations": "off",
      "no-delete-var": "error",
      "no-label-var": "error",
      "no-restricted-globals": "off",
      "no-shadow": "error",
      "no-shadow-restricted-names": "error",
      "no-undef": "error",
      "no-undef-init": "error",
      "no-undefined": "off",
      "no-unused-vars": ["error", { vars: "local", args: "after-used" }],
      "no-use-before-define": "error",
      "react/react-in-jsx-scope": "off",
    },
  },
]);
